### PR TITLE
Bug fix

### LINKED ISSUE #37: User Money gem instead of raw amount
The better way to approach money is to use this gem https://github.com/RubyMoney/money-rails

### LINKED ISSUE #38: ActiveModel::RangeError in ExpertsController#create
81043434343 is out of range for ActiveModel::Type::Integer with limit 4 bytes
change phone number to a string datatype

### LINKED ISSUE #39: no method phone_number
correct the misspell

### LINKED ISSUE #40: Notifier jobs doest kick up on a new talent request

### PR DESCRIPTION
**Pull request by ifebrand6**
fixes #40 
fixes #39 
fixes #38 
fixes #37

### CODE REVIEW

File: app/controllers/dashboard_controller.rb [hunk 1]
```diff
@@ -46,7 +46,7 @@ def finalize_user_request
   private
 
      def final_params
-      params.require(:finalized_request).permit(:user_id, :request_id, talent_assignment_attributes: [:engaged_date, :start_date,:expert_id])
+      params.require(:finalized_request).permit(:user_id, :request_id, talent_assignment_attributes: [:engaged_date, :start_date,:expert_id,:contract_cost])
```
Comment (Innarticles) [inline app/controllers/dashboard_controller.rb:49]: add space `,:contract_cost`

File: app/views/notifier_mailer/send_admitted_msg_for_talent_request.html.erb [hunk 2]
```diff
@@ -4,8 +4,8 @@
     <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
 </head>
 <body>
-    <p>Your request for  <%= @talent_request.talent_type.expert_specialization %>  has been recieved</p>
+    <p>Your request for <% @talent_requests.each do |f|%> <%= f.talent_type.expert_specialization %>   <% end %>has been recieved</p>
     <p>We will get back to you as soon as possible.</p>
     <p>thanks for your patronage.</p>
```
Comment (Innarticles) [inline app/views/notifier_mailer/send_admitted_msg_for_talent_request.html.erb:9]: Thanks

File: app/views/notifier_mailer/send_admitted_msg_for_talent_request.text.erb [hunk 3]
```diff
@@ -1,3 +1,4 @@
-Your request for  <%= @talent_request.talent_type.expert_specialization %> has been recieved
+our request for <% @talent_requests.each do |f|%> <%= f.talent_type.expert_specialization %> <% end %>has been recieved
```
Comment (Innarticles) [inline app/views/notifier_mailer/send_admitted_msg_for_talent_request.text.erb:1]: Your

File: app/views/notifier_mailer/send_mail_to_admin_for_a_talent_request.html.erb [hunk 4]
```diff
@@ -9,12 +9,16 @@
...
     --------------------------
     </p>
-    <p>Talent Demanded: <%= @talent_request.talent_type.expert_specialization %> </p>
-    <p>Unit Price: <%= @talent_request.unit_price %> </p>
-    <p>Quantity Demanded:<%= @talent_request.quantity %> </p>
-    <p>Expecteed Duration of Contract:<%= @talent_request.expected_contract_duration %> </p>
-    <p>Expecteed Start Date:<%= @talent_request.expected_start_date %></p>
-    <p>Date ordered: <%= @talent_request.created_at %></p>
+    <% @talent_requests.each do |f|%>
+   <p> Talent Demanded: <%= f.talent_type.expert_specialization %></p>
```
Comment (Innarticles) [inline app/views/notifier_mailer/send_mail_to_admin_for_a_talent_request.html.erb:13]: indent

File: app/views/notifier_mailer/send_mail_to_admin_for_a_talent_request.text.erb [hunk 5]
```diff
@@ -2,12 +2,14 @@ You got a new request from <%= @request.email %>!
...
 --------------------------
+<% @talent_requests.each do |f|%>
 
-Talent Demanded: <%= @talent_request.talent_type.expert_specialization %>
-Unit Price: <%= @talent_request.unit_price %>
-Quantity Demanded:<%= @talent_request.quantity %>
-Expecteed Duration of Contract:<%= @talent_request.expected_contract_duration %>
-Expecteed Start Date:<%= @talent_request.expected_start_date %>
-Date ordered: <%= @talent_request.created_at %>
+Talent Demanded: <%= f.talent_type.expert_specialization %>
```
Comment (Innarticles) [inline app/views/notifier_mailer/send_mail_to_admin_for_a_talent_request.text.erb:7]: indent
